name: Run Script (Node.js)
description: Runs a script with `npm run`
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  registry-url:
    required: false
    default: ""
    description: Registry URL
  script:
    required: true
    description: Script to run
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Node.js environment
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm
        token: ${{ inputs.token }}

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        NPM_CONFIG_FUND: '0'
        NPM_CONFIG_AUDIT: '0'
        SUPPRESS_SUPPORT: '1'
        NO_UPDATE_NOTIFIER: 'true'

    - name: Run postinstall scripts
      shell: bash
      run: npm rebuild && npm run prepare --if-present
      env:
        NO_UPDATE_NOTIFIER: 'true'

    - name: Run script
      shell: bash
      run: npm run "${{ inputs.script }}"
      env:
        NO_UPDATE_NOTIFIER: 'true'
branding:
  color: blue
  icon: server
