name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Node.js environment
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --omit=dev
      env:
        NO_UPDATE_NOTIFIER: 'true'
branding:
  color: green
  icon: shield
