name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Set up Node.js environment
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --omit=dev
      env:
        NO_UPDATE_NOTIFIER: 'true'
branding:
  color: green
  icon: shield
