name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Node.js environment
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --omit=dev
      env:
        NO_UPDATE_NOTIFIER: 'true'
branding:
  color: green
  icon: shield
