name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7

    - name: Set up Node.js environment
      uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --production
branding:
  color: green
  icon: shield
