name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

    - name: Set up Node.js environment
      uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --production
branding:
  color: green
  icon: shield
