name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

    - name: Set up Node.js environment
      uses: actions/setup-node@86bf502a33df3d7ca5daace2b5d63c9877c85c28
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --production
branding:
  color: green
  icon: shield
