name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up Node.js environment
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --production
branding:
  color: green
  icon: shield
