name: Audit Node.js Packages
description: Audits Node.js packages with `npm audit`
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Node.js environment
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: "lts/*"

    - name: Run audit
      shell: bash
      run: npm audit --omit=dev
      env:
        NO_UPDATE_NOTIFIER: 'true'
branding:
  color: green
  icon: shield
