name: Build and Test (Node.js)
description: Builds and tests a Node.js library or application
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  registry-url:
    required: false
    default: ""
    description: Registry URL
  run-tests:
    required: false
    default: "yes"
    description: Whether to run tests
  skip-checkout:
    required: false
    default: "no"
    description: Whether to checxk out the source code
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      if: ${{ inputs.skip-checkout != 'yes' }}

    - name: Set up Node.js environment
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm
        token: ${{ inputs.token }}

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        NPM_CONFIG_FUND: '0'
        NPM_CONFIG_AUDIT: '0'
        SUPPRESS_SUPPORT: '1'
        NO_UPDATE_NOTIFIER: 'true'

    - name: Run postinstall scripts
      shell: bash
      run: npm rebuild && npm run prepare --if-present
      env:
        NO_UPDATE_NOTIFIER: 'true'

    - name: Run tests
      shell: bash
      run: npm test
      env:
        COLLECT_COVERAGE: '0'
        NO_UPDATE_NOTIFIER: 'true'
      if: ${{ inputs.run-tests == 'yes' }}
branding:
  color: blue
  icon: server
