name: Build and Test (Node.js)
description: Builds and tests a Node.js library or application
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  registry-url:
    required: false
    default: ""
    description: Registry URL
  run-tests:
    required: false
    default: "yes"
    description: Whether to run tests
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

    - name: Set up Node.js environment
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm

    - name: Update npm
      shell: bash
      run: npm i -g npm@latest

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Run postinstall scripts
      shell: bash
      run: npm rebuild && npm run prepare --if-present

    - name: Run tests
      shell: bash
      run: npm test
      env:
        COLLECT_COVERAGE: "0"
      if: ${{ inputs.run-tests == 'yes' }}
branding:
  color: blue
  icon: server
