name: Prepare K8S deployment
description: Adds necessary kustomizations prior to deployment
inputs:
  image_version:
    required: true
    description: Image version (tag) to use
  secret_environment:
    required: true
    description: Base64-encoded environment used to generate secrets
  path:
    required: false
    default: iac
    description: Path to kustomization.yaml
runs:
  using: composite
  steps:
    - name: Create .env
      shell: bash
      run: echo "${SECRET_ENVIRONMENT}" | base64 -d > "${{ inputs.path }}/.env"
      env:
        SECRET_ENVIRONMENT: ${{ inputs.secret_environment }}

    - name: Create patch-image-version.yaml
      shell: bash
      run: cat "${{ inputs.path }}/patch-image-version.yaml.in" | envsubst > "${{ inputs.path }}/patch-image-version.yaml"
      env:
        IMAGE_VERSION: ${{ inputs.image_version }}

    - name: Patch kustomization.yaml
      shell: bash
      run: |
        echo -e "\npatchesStrategicMerge:\n  - 'patch-image-version.yaml'" >> "${{ inputs.path }}/kustomization.yaml"
branding:
  color: blue
  icon: battery-charging
