name: Audit Node.js Packages
description: Audits Node.js packages with `retire.js`
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  registry-url:
    required: false
    default: ""
    description: Registry URL
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

    - name: Set up Node.js environment
      uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Install retire.js
      shell: bash
      run: npm i -g retire

    - name: Run audit
      shell: bash
      run: retire -n
branding:
  color: blue
  icon: shield
