name: Audit Node.js Packages
description: Audits Node.js packages with `retire.js`
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  registry-url:
    required: false
    default: ""
    description: Registry URL
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

    - name: Set up Node.js environment
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Install retire.js
      shell: bash
      run: npm i -g retire

    - name: Run audit
      shell: bash
      run: retire -n
branding:
  color: blue
  icon: shield
