name: SonarScan (Node.js)
description: Run SonarScanner on a Node.js library or application
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  sonar-token:
    required: true
    description: SonarCloud token
  registry-url:
    required: false
    default: ""
    description: Registry URL
  test-script:
    required: false
    default: "test"
    description: npm script to run tests
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Set up Node.js environment
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm
        token: ${{ inputs.token }}

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        NPM_CONFIG_FUND: '0'
        NPM_CONFIG_AUDIT: '0'
        SUPPRESS_SUPPORT: '1'
        NO_UPDATE_NOTIFIER: 'true'

    - name: Run postinstall scripts
      shell: bash
      run: npm rebuild && npm run prepare --if-present

    - name: Run tests
      shell: bash
      run: npm run ${{ inputs.test-script }}
      env:
        COLLECT_COVERAGE: '1'
        SONARSCANNER: 'true'
        NO_UPDATE_NOTIFIER: 'true'

    - name: Retrieve information from package.json
      uses: myrotvorets/info-from-package-json-action@8c0495f8c31c3b5e01e4b5dbb9dddb269089cffb # v2.0.2
      id: ver

    - name: Fix paths in test-report.xml
      run: |
        [ -f test-report.xml ] && sed -i "s@$(pwd)@/github/workspace@g" test-report.xml || true
        [ -f .reports/test-report.xml ] && sed -i "s@$(pwd)@/github/workspace@g" .reports/test-report.xml || true
      shell: bash

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@0303d6b62e310685c0e34d0b9cde218036885c4d # v5.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        args: >
          -Dsonar.projectName=${{ steps.ver.outputs.packageName }}
          -Dsonar.projectVersion=${{ steps.ver.outputs.packageVersion }}
          -Dsonar.links.homepage=${{ steps.ver.outputs.packageHomepage }}
          -Dsonar.links.issue=${{ steps.ver.outputs.packageBugsUrl }}
          -Dsonar.links.scm=${{ steps.ver.outputs.packageScmUrl }}

branding:
  color: blue
  icon: server
