name: SonarScan (Node.js)
description: Run SonarScanner on a Node.js library or application
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  sonar-token:
    required: true
    description: SonarCloud token
  registry-url:
    required: false
    default: ""
    description: Registry URL
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      with:
        fetch-depth: 0

    - name: Set up Node.js environment
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm
        token: ${{ inputs.token }}

    - name: Update npm
      shell: bash
      run: npm i -g npm@latest

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Run postinstall scripts
      shell: bash
      run: npm rebuild && npm run prepare --if-present

    - name: Run tests
      shell: bash
      run: npm test
      env:
        COLLECT_COVERAGE: "1"
        SONARSCANNER: "true"

    - name: Retrieve information from package.json
      uses: myrotvorets/info-from-package-json-action@8e669c68fee193af17ffe3c9e6a028acd6616768 # tag=1.2.0
      id: ver

    - name: Fix paths in test-report.xml
      run: |
        [ -f test-report.xml ] && sed -i "s@$(pwd)@/github/workspace@g" test-report.xml
      shell: bash

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@db501078e936e4b4c8773d1bb949ba9ddb7b6b6a # v1.9
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        args: >
          -Dsonar.projectName=${{ steps.ver.outputs.packageName }}
          -Dsonar.projectVersion=${{ steps.ver.outputs.packageVersion }}
          -Dsonar.links.homepage=${{ steps.ver.outputs.packageHomepage }}
          -Dsonar.links.issue=${{ steps.ver.outputs.packageBugsUrl }}
          -Dsonar.links.scm=${{ steps.ver.outputs.packageScmUrl }}

branding:
  color: blue
  icon: server
