name: Publish Node.js Package
description: Publishes a Node.js package to a registry
inputs:
  token:
    required: false
    default: "${{ github.token }}"
    description: GitHub authentication token
  node-auth-token:
    required: true
    description: Registry authentication token
  registry-url:
    required: false
    default: "https://registry.npmjs.org/"
    description: Registry URL
  commit-sha:
    required: false
    default: "${{ github.sha }}"
    description: SHA of the commit to set the status for
  artifact-name:
    required: false
    default: "package"
    description: Artifact name (.tgz archive to publish)
  archive-name:
    required: false
    default: "*.tgz"
    description: Filename of the archive to publish
  dist-tag:
    required: false
    default: "latest"
    description: Distribution tag to use
runs:
  using: composite
  steps:
    - name: Set commit status to PENDING
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        token: ${{ inputs.token }}
        status: pending
        context: Publish to ${{ inputs.registry-url }}
        sha: ${{ inputs.commit-sha }}
      if: inputs.commit-sha != ''

    - name: Set up Node.js environment
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        registry-url: ${{ inputs.registry-url }}
        node-version: lts/*

    - name: Download tarball
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: ${{ inputs.artifact-name }}

    - name: Set dist-tag
      run: |
        if [ -z "${{ inputs.dist-tag }}" ]; then
          echo "dist-tag=latest" >> "${GITHUB_ENV}"
        else
          echo "dist-tag=${{ inputs.dist-tag }}" >> "${GITHUB_ENV}"
        fi
      shell: bash

    - name: Publish package
      run: npm publish ${{ inputs.archive-name }} --tag '${{ env.dist-tag }}'
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
        NO_UPDATE_NOTIFIER: 'true'

    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        token: ${{ inputs.token }}
        status: ${{ job.status }}
        context: Publish to ${{ inputs.registry-url }}
        sha: ${{ inputs.commit-sha }}
      if: always() && inputs.commit-sha != ''

branding:
  color: blue
  icon: package
