name: Publish Node.js Package
description: Publishes a Node.js package to a registry
inputs:
  token:
    required: false
    default: "${{ github.token }}"
    description: GitHub authentication token
  node-auth-token:
    required: true
    description: Registry authentication token
  registry-url:
    required: false
    default: "https://registry.npmjs.org/"
    description: Registry URL
  commit-sha:
    required: false
    default: "${{ github.sha }}"
    description: SHA of the commit to set the status for
  artifact-name:
    required: false
    default: "package"
    description: Artifact name (.tgz archive to publish)
  archive-name:
    required: false
    default: "*.tgz"
    description: Filename of the archive to publish
runs:
  using: composite
  steps:
    - name: Set commit status to PENDING
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        token: ${{ inputs.token }}
        status: pending
        context: Publish to ${{ inputs.registry-url }}
        sha: ${{ inputs.commit-sha }}
      if: inputs.commit-sha != ''

    - name: Set up Node.js environment
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        registry-url: ${{ inputs.registry-url }}
        node-version: lts/*

    - name: Download tarball
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: ${{ inputs.artifact-name }}

    - name: Publish package
      run: npm publish ${{ inputs.archive-name }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
        NO_UPDATE_NOTIFIER: 'true'

    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        token: ${{ inputs.token }}
        status: ${{ job.status }}
        context: Publish to ${{ inputs.registry-url }}
        sha: ${{ inputs.commit-sha }}
      if: always() && inputs.commit-sha != ''

branding:
  color: blue
  icon: package
