name: Prepublish Node.js Package
description: Prepares a Node.js package for publishing
inputs:
  node-version:
    required: false
    default: "lts/*"
    description: Node.js version
  token:
    required: false
    default: "${{ github.token }}"
    description: Authentication token
  registry-url:
    required: false
    default: ""
    description: Registry URL
  artifact-name:
    required: false
    default: "package"
    description: Artifact name (.tgz archive to publish)
  retention-days:
    required: false
    default: "1"
    description: How long to keep the artifact
outputs:
  filename:
    description: Archive filename
    value: ${{ steps.pack.outputs.filename }}

runs:
  using: composite
  steps:
    - name: Build package
      uses: myrotvorets/composite-actions/build-test-nodejs@master
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        token: ${{ inputs.token }}
        run-tests: no

    - name: Create tarball
      id: pack
      shell: bash
      run: |
        echo "filename=$(npm pack 2> /dev/null)" >> "${GITHUB_OUTPUT}"

    - name: Save tarball
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.pack.outputs.filename }}
        retention-days: ${{ inputs.retention-days }}

branding:
  color: blue
  icon: package
